"""Shared client constants."""

DEFAULT_TIMEOUT_SECONDS = 30.0
MAX_RESPONSE_BODY_BYTES = 8 << 20
DEFAULT_WRONG_MACHINE_MAX = 3
DEFAULT_CREATE_AMBIGUOUS_VERIFY_DELAY = 3.0
API_PREFIX = "/datoriumdb/v1"
DEFAULT_USER_AGENT = "datorium-client-py"
